<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Reeled.Installer</RootNamespace>
    <AssemblyName>ReeledSetup</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;x86;ARM64</Platforms>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-$([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture.ToString().ToLowerInvariant())</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <DefaultLanguage>en-US</DefaultLanguage>
    <Company>k25jura</Company>
    <Authors>k25jura</Authors>
    <Product>Reeled</Product>
    <AssemblyTitle>Reeled Setup</AssemblyTitle>
    <Copyright>Copyright © 2026 k25jura</Copyright>
    <Description>Reeled Setup and Installation Bootstrapper</Description>
    <Version>1.0.0</Version>
    <EnableMsixTooling>true</EnableMsixTooling>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\AppIcon.ico" />
    <Content Include="Assets\reeled.png" />
    <Content Include="Localization\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\*.json" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools.WinApp" Version="0.6.1" />
  </ItemGroup>

  <PropertyGroup>
    <PublishReadyToRun>False</PublishReadyToRun>
    <PublishTrimmed>False</PublishTrimmed>
    <PublishSingleFile Condition="'$(Configuration)' != 'Debug'">True</PublishSingleFile>
    <SelfContained Condition="'$(Configuration)' != 'Debug'">True</SelfContained>
    <IncludeNativeLibrariesForSelfExtract Condition="'$(Configuration)' != 'Debug'">True</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile Condition="'$(Configuration)' != 'Debug'">True</EnableCompressionInSingleFile>
  </PropertyGroup>
</Project>
